name: ecommerce_app
description: "A new Flutter project."
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ^3.11.3

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.8

  # Firebase Core (required for initialization)
  firebase_core: ^3.0.0

  # Firestore Database
  cloud_firestore: ^5.0.0

  # STATE MANAGEMENT (VERY IMPORTANT FOR YOUR CART SYSTEM)
  provider: ^6.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
