// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      throw UnsupportedError(
        'DefaultFirebaseOptions have not been configured for web - '
        'you can reconfigure this by running the FlutterFire CLI again.',
      );
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCdtQWJTHuX_ENGYnizPXTou7Ty4brwKKQ',
    appId: '1:54209686716:android:a806e67280d6ceb868b4b9',
    messagingSenderId: '54209686716',
    projectId: 'ecommerce-app-10327',
    storageBucket: 'ecommerce-app-10327.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDxVFo24qHfIijLJdxNt8pxsBEuPhtxomQ',
    appId: '1:54209686716:ios:1eff6add2c4f1b2568b4b9',
    messagingSenderId: '54209686716',
    projectId: 'ecommerce-app-10327',
    storageBucket: 'ecommerce-app-10327.firebasestorage.app',
    iosBundleId: 'com.saajiddx.ecommerceapp',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDxVFo24qHfIijLJdxNt8pxsBEuPhtxomQ',
    appId: '1:54209686716:ios:4504e6ebc383f36c68b4b9',
    messagingSenderId: '54209686716',
    projectId: 'ecommerce-app-10327',
    storageBucket: 'ecommerce-app-10327.firebasestorage.app',
    iosBundleId: 'com.example.ecommerceApp',
  );
}
